services:
  # Serviço da Aplicação PHP (Laravel)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel
      
  # Serviço do Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend  # Aponta para a pasta do seu projeto Vue
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # Evita que o node_modules local sobrescreva o do contêiner
    ports:
      # Mapeia a porta do Vite/Vue para a sua máquina (para Hot Reload)
      - "5173:5173"
    networks:
      - laravel

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Mapeia a porta 8080 do seu PC para a porta 80 do Nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      # Variáveis de ambiente para criar o banco de dados e o usuário
      # ATENÇÃO: Use senhas seguras em um projeto real.
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: laravel_user
    volumes:
      # Volume nomeado para persistir os dados do banco de dados
      - db_data:/var/lib/mysql
    ports:
      - "33066:3306" # Mapeia a porta 33066 do seu PC para o MySQL (útil para debug)
    networks:
      - laravel

  # Serviço de E-mail para Desenvolvimento (Mailpit)
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./.docker/mailpit/data:/data
    ports:
      - "8025:8025" # Interface web para visualizar e-mails
      - "1025:1025" # Porta SMTP
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - laravel

  # Serviço de Cache e Filas (Redis)
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

# Define a rede customizada para os serviços se comunicarem
networks:
  laravel:
    driver: bridge

# Define o volume nomeado para o banco de dados
volumes:
  db_data:
    driver: local